#
# @file component.mk
# @brief component declaration for esp32
# @author auto-generated by mrt-gatt (https://mrt.readthedocs.io/en/latest/pages/mrtutils/mrt-gatt.html)
# @date 12/13/21
#
#
# include this by adding:
#	EXTRA_COMPONENT_DIRS := path/to/this/dir 
#
# To the root makefile in your project 

COMPONENT_ADD_INCLUDEDIRS := . interface svc
COMPONENT_SRCDIRS := . interface svc 